Twitter {
  VERSION: '1.7.1',
  options:
   { consumer_key: 'FkMc6WwzoOtP3iV0TcZTyLme7',
     consumer_secret: 'lNpOjHl5fj8Y6Scb4kjK4JeuRsgC2Fcu9q4iMq7k7dHQ7QjlXe',
     access_token_key: '1424219396-SNhz7ScfxDq8hAWROjk1BYBeT2UhBOss9HnUfgY',
     access_token_secret: 'OQQaDPMJjoYZiLkVaYAZsjDuVhZoJ1NaxcymXdYhyDoUu',
     bearer_token: null,
     rest_base: 'https://api.twitter.com/1.1',
     stream_base: 'https://stream.twitter.com/1.1',
     user_stream_base: 'https://userstream.twitter.com/1.1',
     site_stream_base: 'https://sitestream.twitter.com/1.1',
     media_base: 'https://upload.twitter.com/1.1',
     request_options: { headers: [Object], oauth: [Object] } },
  request:
   { [Function]
     get: [Function],
     head: [Function],
     post: [Function],
     put: [Function],
     patch: [Function],
     del: [Function],
     delete: [Function],
     cookie: [Function],
     jar: [Function],
     defaults: [Function] },
  allow_promise: true }
[ { created_at: 'Mon Nov 27 17:52:34 +0000 2017',
    id: 935204716698656800,
    id_str: '935204716698656768',
    text: 'Here is another tweet. #RaspberryPi',
    truncated: false,
    entities: { hashtags: [Object], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1424219396,
       id_str: '1424219396',
       name: 'Raspberry Pi',
       screen_name: 'RasPiTime',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 8,
       friends_count: 1,
       listed_count: 2,
       created_at: 'Sun May 12 23:11:18 +0000 2013',
       favourites_count: 5,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 5,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Mon Nov 27 17:52:20 +0000 2017',
    id: 935204657693102100,
    id_str: '935204657693102080',
    text: 'This is tweet 1.',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1424219396,
       id_str: '1424219396',
       name: 'Raspberry Pi',
       screen_name: 'RasPiTime',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 8,
       friends_count: 1,
       listed_count: 2,
       created_at: 'Sun May 12 23:11:18 +0000 2013',
       favourites_count: 5,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 5,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Mon May 13 06:52:38 +0000 2013',
    id: 333837168474726400,
    id_str: '333837168474726402',
    text: 'RT @MattressMack: “Be true to your work, your word, and your friend.”-  Henry David Thoreau',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1424219396,
       id_str: '1424219396',
       name: 'Raspberry Pi',
       screen_name: 'RasPiTime',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 8,
       friends_count: 1,
       listed_count: 2,
       created_at: 'Sun May 12 23:11:18 +0000 2013',
       favourites_count: 5,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 5,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Sun May 12 17:31:27 +0000 2013',
       id: 333635547417428000,
       id_str: '333635547417427970',
       text: '“Be true to your work, your word, and your friend.”-  Henry David Thoreau',
       truncated: false,
       entities: [Object],
       source: '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 3,
       favorited: true,
       retweeted: true,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 5,
    favorite_count: 0,
    favorited: true,
    retweeted: true,
    lang: 'en' },
  { created_at: 'Mon May 13 06:51:33 +0000 2013',
    id: 333836899074576400,
    id_str: '333836899074576384',
    text: 'RT @AP: Judge rules billionaire Ted Turner can keep his Yellowstone National Park bison calves: http://t.co/xqCBte1JgC -RJJ',
    truncated: false,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1424219396,
       id_str: '1424219396',
       name: 'Raspberry Pi',
       screen_name: 'RasPiTime',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 8,
       friends_count: 1,
       listed_count: 2,
       created_at: 'Sun May 12 23:11:18 +0000 2013',
       favourites_count: 5,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 5,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Sun May 12 23:30:07 +0000 2013',
       id: 333725809485426700,
       id_str: '333725809485426689',
       text: 'Judge rules billionaire Ted Turner can keep his Yellowstone National Park bison calves: http://t.co/xqCBte1JgC -RJJ',
       truncated: false,
       entities: [Object],
       source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 47,
       favorite_count: 15,
       favorited: false,
       retweeted: true,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 47,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Sun May 12 23:12:01 +0000 2013',
    id: 333721253653385200,
    id_str: '333721253653385216',
    text: 'This account is updated by a Raspberry Pi.',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1424219396,
       id_str: '1424219396',
       name: 'Raspberry Pi',
       screen_name: 'RasPiTime',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 8,
       friends_count: 1,
       listed_count: 2,
       created_at: 'Sun May 12 23:11:18 +0000 2013',
       favourites_count: 5,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 5,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/3653200733/6f32bd8068fe7ff72ed935eed0755121_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' } ]